language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.1

matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=1.4.20
    - python: 3.3
      env: DJANGO_VERSION=1.4.20
    - python: 2.6
      env: DJANGO_VERSION=1.7.8
    - python: 2.6
      env: DJANGO_VERSION=1.8.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - make lint
  - make test
