language: python

matrix:
  include:
    # Python 2.6 is supported by Django < 1.7
    - python: 2.6
      env: DJANGO_VERSION=1.4.22
    - python: 2.6
      env: DJANGO_VERSION=1.5.12
    - python: 2.6
      env: DJANGO_VERSION=1.6.11
    # Python 2.7 is supported by Django < 2.0
    - python: 2.7
      env: DJANGO_VERSION=1.4.22
    - python: 2.7
      env: DJANGO_VERSION=1.5.12
    - python: 2.7
      env: DJANGO_VERSION=1.6.11
    - python: 2.7
      env: DJANGO_VERSION=1.7.11
    - python: 2.7
      env: DJANGO_VERSION=1.8.19
    - python: 2.7
      env: DJANGO_VERSION=1.9.13
    - python: 2.7
      env: DJANGO_VERSION=1.10.8
    - python: 2.7
      env: DJANGO_VERSION=1.11.15
    # Python 3.3 is supported by Django >= 1.5 and Django < 1.9
    - python: 3.3
      env: DJANGO_VERSION=1.5.12
    - python: 3.3
      env: DJANGO_VERSION=1.6.11
    - python: 3.3
      env: DJANGO_VERSION=1.7.11
    - python: 3.3
      env: DJANGO_VERSION=1.8.19
    # Python 3.4 is supported by Django >= 1.5 and Django < 1.11
    - python: 3.4
      env: DJANGO_VERSION=1.5.12
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
    - python: 3.4
      env: DJANGO_VERSION=1.7.11
    - python: 3.4
      env: DJANGO_VERSION=1.8.19
    - python: 3.4
      env: DJANGO_VERSION=1.9.13
    - python: 3.4
      env: DJANGO_VERSION=1.10.8
    # Python 3.5 is supported by Django >= 1.8
    - python: 3.5
      env: DJANGO_VERSION=1.8.19
    - python: 3.5
      env: DJANGO_VERSION=1.9.13
    - python: 3.5
      env: DJANGO_VERSION=1.10.8
    - python: 3.5
      env: DJANGO_VERSION=1.11.15
    - python: 3.5
      env: DJANGO_VERSION=2.0.8
    - python: 3.5
      env: DJANGO_VERSION=2.1
    # Python 3.6 is supported by Django >= 1.11
    - python: 3.6
      env: DJANGO_VERSION=1.11.15
    - python: 3.6
      env: DJANGO_VERSION=2.0.8
    - python: 3.6
      env: DJANGO_VERSION=2.1
    # Python 3.7 is supported by Django >= 2.0
    # The dist and sudo are needed to run 3.7
    # on Travis until 3.7 is officially supported.
    - python: 3.7
      env: DJANGO_VERSION=2.0.8
      dist: xenial
      sudo: true
    - python: 3.7
      env: DJANGO_VERSION=2.1
      dist: xenial
      sudo: true

install:
  - pip install --pre -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - make lint
  - make test
