language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.19
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.14
  - DJANGO_VERSION=2.0.8


matrix:
  include:
    # Python 2.6 is supported by Django < 1.7
    - python: 2.6
      env: DJANGO_VERSION=1.4.22
    - python: 2.6
      env: DJANGO_VERSION=1.5.12
    - python: 2.6
      env: DJANGO_VERSION=1.6.11
    # Python 2.7 is supported by Django < 2.0
    - python: 2.7
      env: DJANGO_VERSION=1.4.22
    - python: 2.7
      env: DJANGO_VERSION=1.5.12
    - python: 2.7
      env: DJANGO_VERSION=1.6.11
    - python: 2.7
      env: DJANGO_VERSION=1.7.11
    - python: 2.7
      env: DJANGO_VERSION=1.8.19
    - python: 2.7
      env: DJANGO_VERSION=1.9.13
    - python: 2.7
      env: DJANGO_VERSION=1.10.8
    - python: 2.7
      env: DJANGO_VERSION=1.11.14
    # Python 3.3 is supported by Django >= 1.5 and Django < 1.9
    - python: 3.3
      env: DJANGO_VERSION=1.5.12
    - python: 3.3
      env: DJANGO_VERSION=1.6.11
    - python: 3.3
      env: DJANGO_VERSION=1.7.11
    - python: 3.3
      env: DJANGO_VERSION=1.8.19
    # Python 3.4 is supported by Django >= 1.5 and Django < 1.11
    - python: 3.4
      env: DJANGO_VERSION=1.5.12
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
    - python: 3.4
      env: DJANGO_VERSION=1.7.11
    - python: 3.4
      env: DJANGO_VERSION=1.8.19
    - python: 3.4
      env: DJANGO_VERSION=1.9.13
    - python: 3.4
      env: DJANGO_VERSION=1.10.8
    # Python 3.5 is supported by Django >= 1.8
    - python: 3.5
      env: DJANGO_VERSION=1.8.19
    - python: 3.5
      env: DJANGO_VERSION=1.9.13
    - python: 3.5
      env: DJANGO_VERSION=1.10.8
    - python: 3.5
      env: DJANGO_VERSION=1.11.14
    - python: 3.5
      env: DJANGO_VERSION=2.0.8
    # Python 3.6 is supported by Django >= 1.11
    - python: 3.6
      env: DJANGO_VERSION=1.11.14
    - python: 3.6
      env: DJANGO_VERSION=2.0.8
    # Python 3.7 is supported by Django >= 2.0
    - python: 3.7
      env: DJANGO_VERSION=2.0.8

install:
  - pip install --pre -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - make lint
  - make test
