language: python

matrix:
  include:
    # Python 2.6 is supported by Django < 1.7
    - python: 2.6
      env: DJANGO_VERSION=1.4.22
    - python: 2.6
      env: DJANGO_VERSION=1.5.12
    - python: 2.6
      env: DJANGO_VERSION=1.6.11
    # Python 2.7 is supported by Django < 2.0
    - python: 2.7
      env: DJANGO_VERSION=1.4.22
    - python: 2.7
      env: DJANGO_VERSION=1.5.12
    - python: 2.7
      env: DJANGO_VERSION=1.6.11
    - python: 2.7
      env: DJANGO_VERSION=1.7.11
    - python: 2.7
      env: DJANGO_VERSION=1.8.19
    - python: 2.7
      env: DJANGO_VERSION=1.9.13
    - python: 2.7
      env: DJANGO_VERSION=1.10.8
    - python: 2.7
      env: DJANGO_VERSION=1.11.29
    # Python 3.3 is supported by Django >= 1.5 and Django < 1.9
    - python: 3.3
      env: DJANGO_VERSION=1.5.12
    - python: 3.3
      env: DJANGO_VERSION=1.6.11
    - python: 3.3
      env: DJANGO_VERSION=1.7.11
    - python: 3.3
      env: DJANGO_VERSION=1.8.19
    # Python 3.4 is supported by Django >= 1.5 and Django < 1.11
    - python: 3.4
      env: DJANGO_VERSION=1.5.12
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
    - python: 3.4
      env: DJANGO_VERSION=1.7.11
    - python: 3.4
      env: DJANGO_VERSION=1.8.19
    - python: 3.4
      env: DJANGO_VERSION=1.9.13
    - python: 3.4
      env: DJANGO_VERSION=1.10.8
    # Python 3.5 is supported by Django >= 1.8 and Django < 3.0
    - python: 3.5
      env: DJANGO_VERSION=1.8.19
    - python: 3.5
      env: DJANGO_VERSION=1.9.13
    - python: 3.5
      env: DJANGO_VERSION=1.10.8
    - python: 3.5
      env: DJANGO_VERSION=1.11.29
    - python: 3.5
      env: DJANGO_VERSION=2.0.13
    - python: 3.5
      env: DJANGO_VERSION=2.1.15
    - python: 3.5
      env: DJANGO_VERSION=2.2.24
    # Python 3.6 is supported by Django >= 1.11
    - python: 3.6
      env: DJANGO_VERSION=1.11.29
    - python: 3.6
      env: DJANGO_VERSION=2.0.13
    - python: 3.6
      env: DJANGO_VERSION=2.1.15
    - python: 3.6
      env: DJANGO_VERSION=2.2.24
    - python: 3.6
      env: DJANGO_VERSION=3.0.14
    - python: 3.6
      env: DJANGO_VERSION=3.1.13
    - python: 3.6
      env: DJANGO_VERSION=3.2.8
    # Python 3.7 is supported by Django >= 2.0
    - python: 3.7
      env: DJANGO_VERSION=2.0.13
    - python: 3.7
      env: DJANGO_VERSION=2.1.15
    - python: 3.7
      env: DJANGO_VERSION=2.2.24
    - python: 3.7
      env: DJANGO_VERSION=3.0.14
    - python: 3.7
      env: DJANGO_VERSION=3.1.13
    - python: 3.7
      env: DJANGO_VERSION=3.2.8
    # Python 3.8 is supported by Django >= 2.2
    - python: 3.8
      env: DJANGO_VERSION=2.2.24
    - python: 3.8
      env: DJANGO_VERSION=3.0.14
    - python: 3.8
      env: DJANGO_VERSION=3.1.13
    - python: 3.8
      env: DJANGO_VERSION=3.2.8
    # Python 3.8 is supported by Django >= 2.2
    - python: 3.9
      env: DJANGO_VERSION=2.2.24
    - python: 3.9
      env: DJANGO_VERSION=3.0.14
    - python: 3.9
      env: DJANGO_VERSION=3.1.13
    - python: 3.9
      env: DJANGO_VERSION=3.2.8

install:
  - pip install --pre -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - make lint
  - make test
